namespace SkyEditor.RomEditor.Domain.Rtdx.Constants
{
	public enum RankIndex
 	{
 		RANK_POINT_RANK_NONE,
 		RANK_POINT_RANK_01,
 		RANK_POINT_RANK_02,
 		RANK_POINT_RANK_03,
 		RANK_POINT_RANK_04,
 		RANK_POINT_RANK_05,
 		RANK_POINT_RANK_06,
 		RANK_POINT_RANK_07,
 		RANK_POINT_RANK_08,
 		RANK_POINT_RANK_09,
 		RANK_POINT_RANK_10,
 		RANK_POINT_RANK_11,
 		RANK_POINT_RANK_12,
 		RANK_END
 	}
} 
