//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyEditor.RomEditor.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EffectType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EffectType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyEditor.RomEditor.Resources.Strings.EffectType", typeof(EffectType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a type to the target.
        /// </summary>
        public static string AddType {
            get {
                return ResourceManager.GetString("AddType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant Protect to user and all teammates; duration depends on team size.
        /// </summary>
        public static string AllProtect {
            get {
                return ResourceManager.GetString("AllProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the specified dungeon status.
        /// </summary>
        public static string ApplyDungeonStatus {
            get {
                return ResourceManager.GetString("ApplyDungeonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply freeze, burn or paralysis.
        /// </summary>
        public static string ApplyFreezeBurnOrParalysis {
            get {
                return ResourceManager.GetString("ApplyFreezeBurnOrParalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the Grounded status effect.
        /// </summary>
        public static string ApplyGrounded {
            get {
                return ResourceManager.GetString("ApplyGrounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply dungeon status effect if another teammate has used a matching Pledge move.
        /// </summary>
        public static string ApplyPledgeEffect {
            get {
                return ResourceManager.GetString("ApplyPledgeEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a random stat change.
        /// </summary>
        public static string ApplyRandomStatChange {
            get {
                return ResourceManager.GetString("ApplyRandomStatChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply stat changes.
        /// </summary>
        public static string ApplyStatChanges {
            get {
                return ResourceManager.GetString("ApplyStatChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply stat changes; double if under specified weather.
        /// </summary>
        public static string ApplyStatChangesWithWeatherBoost {
            get {
                return ResourceManager.GetString("ApplyStatChangesWithWeatherBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply status effect unconditionally.
        /// </summary>
        public static string ApplyStatusEffect {
            get {
                return ResourceManager.GetString("ApplyStatusEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply status effect based on current location.
        /// </summary>
        public static string ApplyStatusEffectBasedOnLocation {
            get {
                return ResourceManager.GetString("ApplyStatusEffectBasedOnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply status effect to summoned monsters.
        /// </summary>
        public static string ApplyStatusEffectToSummonedMonsters {
            get {
                return ResourceManager.GetString("ApplyStatusEffectToSummonedMonsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance to apply status effect.
        /// </summary>
        public static string ApplyStatusEffectWithChance {
            get {
                return ResourceManager.GetString("ApplyStatusEffectWithChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance to apply status effect.
        /// </summary>
        public static string ApplyStatusEffectWithChance2 {
            get {
                return ResourceManager.GetString("ApplyStatusEffectWithChance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance to apply status effect with an additional unknown parameter.
        /// </summary>
        public static string ApplyStatusEffectWithChanceAndSomethingElse {
            get {
                return ResourceManager.GetString("ApplyStatusEffectWithChanceAndSomethingElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Attack and Special Attack stats, replacing both attacker&apos;s and target&apos;s stats.
        /// </summary>
        public static string AverageAttackAndSpecialAttack {
            get {
                return ResourceManager.GetString("AverageAttackAndSpecialAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Defense and Special Defense stats, replacing both attacker&apos;s and target&apos;s stats.
        /// </summary>
        public static string AverageDefenseAndSpecialDefense {
            get {
                return ResourceManager.GetString("AverageDefenseAndSpecialDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly apply Stuck, Poison, Paralysis or Burn.
        /// </summary>
        public static string BadFoodStatus {
            get {
                return ResourceManager.GetString("BadFoodStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal basic attack damage.
        /// </summary>
        public static string BasicAttackDamage {
            get {
                return ResourceManager.GetString("BasicAttackDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin or end storing damage taken.
        /// </summary>
        public static string BeginEndStoringDamage {
            get {
                return ResourceManager.GetString("BeginEndStoringDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blow away target up to 10 tiles and cause 5 damage on collision.
        /// </summary>
        public static string BlowAwayTarget {
            get {
                return ResourceManager.GetString("BlowAwayTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user&apos;s type to its first move&apos;s type.
        /// </summary>
        public static string ChangeToFirstMoveType {
            get {
                return ResourceManager.GetString("ChangeToFirstMoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user&apos;s type to one that has defensive advantage against the target&apos;s last used move.
        /// </summary>
        public static string ChangeToTypeWithAdvantageOverLastMove {
            get {
                return ResourceManager.GetString("ChangeToTypeWithAdvantageOverLastMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change target&apos;s type.
        /// </summary>
        public static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user&apos;s type based on the dungeon.
        /// </summary>
        public static string ChangeTypeBasedOnDungeon {
            get {
                return ResourceManager.GetString("ChangeTypeBasedOnDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate charged move.
        /// </summary>
        public static string ChargedMove {
            get {
                return ResourceManager.GetString("ChargedMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause the action to fail if the belly is empty.
        /// </summary>
        public static string CheckBellyNotEmpty {
            get {
                return ResourceManager.GetString("CheckBellyNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove sticky status from all items.
        /// </summary>
        public static string CleanseStickyItems {
            get {
                return ResourceManager.GetString("CleanseStickyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all water/magma tiles on the floor.
        /// </summary>
        public static string ClearAllWaterAndMagma {
            get {
                return ResourceManager.GetString("ClearAllWaterAndMagma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear stat changes.
        /// </summary>
        public static string ClearStatChanges {
            get {
                return ResourceManager.GetString("ClearStatChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset stockpile count to zero and remove defense boosts.
        /// </summary>
        public static string ClearStockpile {
            get {
                return ResourceManager.GetString("ClearStockpile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert a Plain Seed into another seed or an Oran Berry.
        /// </summary>
        public static string ConvertPlainSeedToOtherFood {
            get {
                return ResourceManager.GetString("ConvertPlainSeedToOtherFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy target&apos;s last used move.
        /// </summary>
        public static string CopyLastUsedMove {
            get {
                return ResourceManager.GetString("CopyLastUsedMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy target&apos;s stat changes.
        /// </summary>
        public static string CopyTargetStatChanges {
            get {
                return ResourceManager.GetString("CopyTargetStatChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy target&apos;s type.
        /// </summary>
        public static string CopyType {
            get {
                return ResourceManager.GetString("CopyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the current room into a Monster House.
        /// </summary>
        public static string CreateMonsterHouse {
            get {
                return ResourceManager.GetString("CreateMonsterHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage; always super-effective against Water types.
        /// </summary>
        public static string DamageAlwaysSuperEffectiveAgainstWater {
            get {
                return ResourceManager.GetString("DamageAlwaysSuperEffectiveAgainstWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove target&apos;s Reflect/Light Screen and deal random typed damage.
        /// </summary>
        public static string DamageAndBreakDefenses {
            get {
                return ResourceManager.GetString("DamageAndBreakDefenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage and apply further effects if target is defeated.
        /// </summary>
        public static string DamageAndContinueActionOnDefeat {
            get {
                return ResourceManager.GetString("DamageAndContinueActionOnDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage; target drops Poké if defeated.
        /// </summary>
        public static string DamageAndDropMoney {
            get {
                return ResourceManager.GetString("DamageAndDropMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage and cause an explosion.
        /// </summary>
        public static string DamageAndExplode {
            get {
                return ResourceManager.GetString("DamageAndExplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal fixed damage and fall to the next floor.
        /// </summary>
        public static string DamageAndFallToNextFloor {
            get {
                return ResourceManager.GetString("DamageAndFallToNextFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier based on how lighter the target is compared to the attacker.
        /// </summary>
        public static string DamageBasedOnAttackerAndTargetWeights {
            get {
                return ResourceManager.GetString("DamageBasedOnAttackerAndTargetWeights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage based on the attacker&apos;s level.
        /// </summary>
        public static string DamageBasedOnAttackersLevel {
            get {
                return ResourceManager.GetString("DamageBasedOnAttackersLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage based on the target&apos;s weight; damage is increased the heavier the target is.
        /// </summary>
        public static string DamageBasedOnTargetsWeight {
            get {
                return ResourceManager.GetString("DamageBasedOnTargetsWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage equal to attacker&apos;s level.
        /// </summary>
        public static string DamageEqualToAttackersLevel {
            get {
                return ResourceManager.GetString("DamageEqualToAttackersLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage if the target shares a type with the user.
        /// </summary>
        public static string DamageIfTargetSharesTypeWithAttacker {
            get {
                return ResourceManager.GetString("DamageIfTargetSharesTypeWithAttacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage, ignoring Protect.
        /// </summary>
        public static string DamageIgnoreProtect {
            get {
                return ResourceManager.GetString("DamageIgnoreProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage ignoring target&apos;s Defense and Evasion stat changes.
        /// </summary>
        public static string DamageIgnoringDefenseAndEvasion {
            get {
                return ResourceManager.GetString("DamageIgnoringDefenseAndEvasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage equal to a percentage of target&apos;s current HP.
        /// </summary>
        public static string DamagePercentageCurrentHP {
            get {
                return ResourceManager.GetString("DamagePercentageCurrentHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage.
        /// </summary>
        public static string DamageThrow {
            get {
                return ResourceManager.GetString("DamageThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage until attack misses.
        /// </summary>
        public static string DamageUntilMiss {
            get {
                return ResourceManager.GetString("DamageUntilMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage using target&apos;s Defense.
        /// </summary>
        public static string DamageUsingDefense {
            get {
                return ResourceManager.GetString("DamageUsingDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage using the target&apos;s Attack stat.
        /// </summary>
        public static string DamageUsingTargetsAttack {
            get {
                return ResourceManager.GetString("DamageUsingTargetsAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier based on attacker&apos;s HP.
        /// </summary>
        public static string DamageWithBoostBasedOnAttackersHP {
            get {
                return ResourceManager.GetString("DamageWithBoostBasedOnAttackersHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier based on the attacker&apos;s number of depleted moves.
        /// </summary>
        public static string DamageWithBoostBasedOnDepletedMoves {
            get {
                return ResourceManager.GetString("DamageWithBoostBasedOnDepletedMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier based on the number of dungeons visited by the attacker.
        /// </summary>
        public static string DamageWithBoostBasedOnDungeonsVisited {
            get {
                return ResourceManager.GetString("DamageWithBoostBasedOnDungeonsVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with a multiplier if there are many enemies nearby.
        /// </summary>
        public static string DamageWithBoostBasedOnNumberOfEnemiesNearby {
            get {
                return ResourceManager.GetString("DamageWithBoostBasedOnNumberOfEnemiesNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier based on the number of positive stat changes of the attacker or target.
        /// </summary>
        public static string DamageWithBoostBasedOnPositiveStatChanges {
            get {
                return ResourceManager.GetString("DamageWithBoostBasedOnPositiveStatChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if the move&apos;s PP is below the threshold.
        /// </summary>
        public static string DamageWithBoostBasedOnPP {
            get {
                return ResourceManager.GetString("DamageWithBoostBasedOnPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier based on target&apos;s HP.
        /// </summary>
        public static string DamageWithBoostBasedOnTargetsHP {
            get {
                return ResourceManager.GetString("DamageWithBoostBasedOnTargetsHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with an increased recruitment rate on defeat.
        /// </summary>
        public static string DamageWithBoostedRecruitRate {
            get {
                return ResourceManager.GetString("DamageWithBoostedRecruitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier based on how faster the attacker is compared to the target.
        /// </summary>
        public static string DamageWithBoostIfFaster {
            get {
                return ResourceManager.GetString("DamageWithBoostIfFaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with a multiplier if the move is used in any weather other than Clear.
        /// </summary>
        public static string DamageWithBoostIfNotClearWeather {
            get {
                return ResourceManager.GetString("DamageWithBoostIfNotClearWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if attacker is not holding an item.
        /// </summary>
        public static string DamageWithBoostIfNotHoldingItem {
            get {
                return ResourceManager.GetString("DamageWithBoostIfNotHoldingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage with multiplier if the move missed in the last turn.
        /// </summary>
        public static string DamageWithBoostIfPreviousTurnMissed {
            get {
                return ResourceManager.GetString("DamageWithBoostIfPreviousTurnMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier based on how slower the attacker is compared to the target.
        /// </summary>
        public static string DamageWithBoostIfSlower {
            get {
                return ResourceManager.GetString("DamageWithBoostIfSlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if the target has any status effect.
        /// </summary>
        public static string DamageWithBoostIfTargetHasAnyStatus {
            get {
                return ResourceManager.GetString("DamageWithBoostIfTargetHasAnyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if the target is afflicted with Burn or Poison.
        /// </summary>
        public static string DamageWithBoostIfTargetHasBurnOrPoison {
            get {
                return ResourceManager.GetString("DamageWithBoostIfTargetHasBurnOrPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if target is afflicted with an specific status.
        /// </summary>
        public static string DamageWithBoostIfTargetHasStatus {
            get {
                return ResourceManager.GetString("DamageWithBoostIfTargetHasStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if the target is holding an item.
        /// </summary>
        public static string DamageWithBoostIfTargetHoldsItem {
            get {
                return ResourceManager.GetString("DamageWithBoostIfTargetHoldsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if target is in the semi-invulnerable turn of Bounce, Fly, and Sky Drop.
        /// </summary>
        public static string DamageWithBoostIfTargetIsFlying {
            get {
                return ResourceManager.GetString("DamageWithBoostIfTargetIsFlying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if the target&apos;s HP is at or below the threshold.
        /// </summary>
        public static string DamageWithBoostIfTargetsHPIsAtOrBelowThreshold {
            get {
                return ResourceManager.GetString("DamageWithBoostIfTargetsHPIsAtOrBelowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if the move is used consecutively.
        /// </summary>
        public static string DamageWithBoostOnConsecutiveUses {
            get {
                return ResourceManager.GetString("DamageWithBoostOnConsecutiveUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if the move was used by a teammate on the same turn.
        /// </summary>
        public static string DamageWithBoostWhenTeammateUsedTheMoveInTheSameTurn {
            get {
                return ResourceManager.GetString("DamageWithBoostWhenTeammateUsedTheMoveInTheSameTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if the move was used by a teammate on the same turn and in the same room.
        /// </summary>
        public static string DamageWithBoostWhenTeammateUsedTheMoveInTheSameTurnInTheSameRoom {
            get {
                return ResourceManager.GetString("DamageWithBoostWhenTeammateUsedTheMoveInTheSameTurnInTheSameRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with a multiplier if the move is used under Rain, Sandstorm or Hail.
        /// </summary>
        public static string DamageWithModifierUnderBadWeather {
            get {
                return ResourceManager.GetString("DamageWithModifierUnderBadWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with type based on the attacker&apos;s held item.
        /// </summary>
        public static string DamageWithTypeBasedOnHeldItem {
            get {
                return ResourceManager.GetString("DamageWithTypeBasedOnHeldItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin charging dark spires attack.
        /// </summary>
        public static string DarkMatterChargingStart {
            get {
                return ResourceManager.GetString("DarkMatterChargingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage equal to the amount of HP that would be lost to reach the target value.
        /// </summary>
        public static string DealDamageEqualToLostHP {
            get {
                return ResourceManager.GetString("DealDamageEqualToLostHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage to creatures surrounding the target.
        /// </summary>
        public static string DealDamageToSurroundingTargets {
            get {
                return ResourceManager.GetString("DealDamageToSurroundingTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage stored by Bide/Revenge/Avalanche.
        /// </summary>
        public static string DealStoredDamage {
            get {
                return ResourceManager.GetString("DealStoredDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease target&apos;s belly.
        /// </summary>
        public static string DecreaseBelly {
            get {
                return ResourceManager.GetString("DecreaseBelly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease target&apos;s level.
        /// </summary>
        public static string DecreaseLevel {
            get {
                return ResourceManager.GetString("DecreaseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy all traps on the floor.
        /// </summary>
        public static string DestroyAllTraps {
            get {
                return ResourceManager.GetString("DestroyAllTraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy target&apos;s food.
        /// </summary>
        public static string DestroyTargetsFood {
            get {
                return ResourceManager.GetString("DestroyTargetsFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dig walls.
        /// </summary>
        public static string DigWalls {
            get {
                return ResourceManager.GetString("DigWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable the target&apos;s last used move for everyone.
        /// </summary>
        public static string DisableMove {
            get {
                return ResourceManager.GetString("DisableMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drain all PP of a random move.
        /// </summary>
        public static string DrainPP {
            get {
                return ResourceManager.GetString("DrainPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force target to drop held item.
        /// </summary>
        public static string DropItem {
            get {
                return ResourceManager.GetString("DropItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force target to drop items.
        /// </summary>
        public static string DropItems {
            get {
                return ResourceManager.GetString("DropItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eat target&apos;s food.
        /// </summary>
        public static string EatTargetsFood {
            get {
                return ResourceManager.GetString("EatTargetsFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce target&apos;s HP to user&apos;s HP if the user has less HP than the target.
        /// </summary>
        public static string EqualizeHP {
            get {
                return ResourceManager.GetString("EqualizeHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the dungeon.
        /// </summary>
        public static string ExitDungeon {
            get {
                return ResourceManager.GetString("ExitDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause an explosion.
        /// </summary>
        public static string Explode {
            get {
                return ResourceManager.GetString("Explode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unconfirmed) Final effect of Magnetic Flux.
        /// </summary>
        public static string FinishMagneticFlux {
            get {
                return ResourceManager.GetString("FinishMagneticFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unconfirmed) Final effect of Flower Shield .
        /// </summary>
        public static string FinishTypeSelect1 {
            get {
                return ResourceManager.GetString("FinishTypeSelect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unconfirmed) Final effect of Rototiller.
        /// </summary>
        public static string FinishTypeSelect2 {
            get {
                return ResourceManager.GetString("FinishTypeSelect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal fixed damage.
        /// </summary>
        public static string FixedDamage {
            get {
                return ResourceManager.GetString("FixedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fling an item.
        /// </summary>
        public static string FlingItem {
            get {
                return ResourceManager.GetString("FlingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Gold Bars and rare items if the leader is holding a Gold Scope.
        /// </summary>
        public static string GiveGoldOrRareItem {
            get {
                return ResourceManager.GetString("GiveGoldOrRareItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give held item to target.
        /// </summary>
        public static string GiveItemToTarget {
            get {
                return ResourceManager.GetString("GiveItemToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal self for a percentage of damage dealt.
        /// </summary>
        public static string HealSelfBasedOnDamageDealt {
            get {
                return ResourceManager.GetString("HealSelfBasedOnDamageDealt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puts the target to sleep; applies Terrified on NPCs or Puppet on the player if already sleeping.
        /// </summary>
        public static string Hypnosis {
            get {
                return ResourceManager.GetString("Hypnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase target&apos;s level.
        /// </summary>
        public static string IncreaseLevel {
            get {
                return ResourceManager.GetString("IncreaseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase max HP.
        /// </summary>
        public static string IncreaseMaxHP {
            get {
                return ResourceManager.GetString("IncreaseMaxHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase a move&apos;s accuracy.
        /// </summary>
        public static string IncreaseMoveAccuracy {
            get {
                return ResourceManager.GetString("IncreaseMoveAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase a move&apos;s power.
        /// </summary>
        public static string IncreaseMovePower {
            get {
                return ResourceManager.GetString("IncreaseMovePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase a move&apos;s PP.
        /// </summary>
        public static string IncreaseMovePP {
            get {
                return ResourceManager.GetString("IncreaseMovePP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase a random stat, with a chance for a bigger increase.
        /// </summary>
        public static string IncreaseRandomStat {
            get {
                return ResourceManager.GetString("IncreaseRandomStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase max HP, Attack, Defense, Special Attack, Special Defense or Speed at random.
        /// </summary>
        public static string IncreaseRandomStats {
            get {
                return ResourceManager.GetString("IncreaseRandomStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase stat.
        /// </summary>
        public static string IncreaseStat {
            get {
                return ResourceManager.GetString("IncreaseStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflict a random status condition or reduce a random stat on a random target.
        /// </summary>
        public static string InflictRandomStatusOrReduceRandomStat {
            get {
                return ResourceManager.GetString("InflictRandomStatusOrReduceRandomStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage based on a random magnitude.
        /// </summary>
        public static string MagnitudeDamage {
            get {
                return ResourceManager.GetString("MagnitudeDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make target&apos;s held item or a random item in the player&apos;s inventory sticky.
        /// </summary>
        public static string MakeItemSticky {
            get {
                return ResourceManager.GetString("MakeItemSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify stats.
        /// </summary>
        public static string ModifyStats {
            get {
                return ResourceManager.GetString("ModifyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set target&apos;s HP to a percentage of current HP.
        /// </summary>
        public static string MultiplyHPByPercentage {
            get {
                return ResourceManager.GetString("MultiplyHPByPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal one-hit KO damage.
        /// </summary>
        public static string OneHitKO {
            get {
                return ResourceManager.GetString("OneHitKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the entire floor into one giant room.
        /// </summary>
        public static string OneRoom {
            get {
                return ResourceManager.GetString("OneRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Bank window.
        /// </summary>
        public static string OpenBank {
            get {
                return ResourceManager.GetString("OpenBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Kangaskhan storage window.
        /// </summary>
        public static string OpenKangaskhanStorage {
            get {
                return ResourceManager.GetString("OpenKangaskhanStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Rescue Team Camps window.
        /// </summary>
        public static string OpenRescueTeamCamps {
            get {
                return ResourceManager.GetString("OpenRescueTeamCamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the Petrify status effect to all targets.
        /// </summary>
        public static string PetrifyAllTargets {
            get {
                return ResourceManager.GetString("PetrifyAllTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal random damage with multiplier if another teammate used a Pledge move in the same turn.
        /// </summary>
        public static string PledgeBoostedDamage {
            get {
                return ResourceManager.GetString("PledgeBoostedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unconfirmed) Select only targets that have the Plus or Minus ability.
        /// </summary>
        public static string PlusAndMinusSelect {
            get {
                return ResourceManager.GetString("PlusAndMinusSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly deal damage or heal.
        /// </summary>
        public static string PresentDamageOrHeal {
            get {
                return ResourceManager.GetString("PresentDamageOrHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull all items on the floor toward the user.
        /// </summary>
        public static string PullAllItems {
            get {
                return ResourceManager.GetString("PullAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull all targets in the room together.
        /// </summary>
        public static string PullTargetsTogether {
            get {
                return ResourceManager.GetString("PullTargetsTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull user towards target.
        /// </summary>
        public static string PullTowardsTarget {
            get {
                return ResourceManager.GetString("PullTowardsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce the effects of a random trap.
        /// </summary>
        public static string RandomTrapEffect {
            get {
                return ResourceManager.GetString("RandomTrapEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take recoil damage.
        /// </summary>
        public static string RecoilDamage {
            get {
                return ResourceManager.GetString("RecoilDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take recoil damage on miss.
        /// </summary>
        public static string RecoilDamageOnMiss {
            get {
                return ResourceManager.GetString("RecoilDamageOnMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower belly to the specified value and maximize Attack modifier.
        /// </summary>
        public static string ReduceBellyAndMaximizeAttack {
            get {
                return ResourceManager.GetString("ReduceBellyAndMaximizeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce user&apos;s HP to 1.
        /// </summary>
        public static string ReduceHPToOne {
            get {
                return ResourceManager.GetString("ReduceHPToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce PP of target&apos;s last used move.
        /// </summary>
        public static string ReducePP {
            get {
                return ResourceManager.GetString("ReducePP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all negative status effects and remove seals.
        /// </summary>
        public static string RemoveAllNegativeStatusEffects {
            get {
                return ResourceManager.GetString("RemoveAllNegativeStatusEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unconfirmed) Remove Flying type temporarily.
        /// </summary>
        public static string RemoveFlyingType {
            get {
                return ResourceManager.GetString("RemoveFlyingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove status effect.
        /// </summary>
        public static string RemoveStatusEffect {
            get {
                return ResourceManager.GetString("RemoveStatusEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove type.
        /// </summary>
        public static string RemoveType {
            get {
                return ResourceManager.GetString("RemoveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace target&apos;s Ability with user&apos;s Ability.
        /// </summary>
        public static string ReplaceTargetAbility {
            get {
                return ResourceManager.GetString("ReplaceTargetAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace user&apos;s Ability with target&apos;s Ability.
        /// </summary>
        public static string ReplaceUserAbility {
            get {
                return ResourceManager.GetString("ReplaceUserAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace move with target&apos;s last used move.
        /// </summary>
        public static string ReplaceWithLastUsedMove {
            get {
                return ResourceManager.GetString("ReplaceWithLastUsedMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all lowered stats.
        /// </summary>
        public static string ResetLoweredStats {
            get {
                return ResourceManager.GetString("ResetLoweredStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset positive Evasion stat changes to zero.
        /// </summary>
        public static string ResetPositiveEvasion {
            get {
                return ResourceManager.GetString("ResetPositiveEvasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawn all defeated teammates.
        /// </summary>
        public static string RespawnDefeatedTeammates {
            get {
                return ResourceManager.GetString("RespawnDefeatedTeammates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore belly and increase max belly if fully sated.
        /// </summary>
        public static string RestoreAndIncreaseBelly {
            get {
                return ResourceManager.GetString("RestoreAndIncreaseBelly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal HP and increase max HP until the threshold; increase max HP further if HP is at max above the threshold.
        /// </summary>
        public static string RestoreAndIncreaseHP {
            get {
                return ResourceManager.GetString("RestoreAndIncreaseHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully heal HP and remove all negative status conditions.
        /// </summary>
        public static string RestoreFullHPAndHealAllNegativeStatusEffects {
            get {
                return ResourceManager.GetString("RestoreFullHPAndHealAllNegativeStatusEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully heal HP and PP and remove all negative status conditions.
        /// </summary>
        public static string RestoreFullHPAndPPAndHealAllNegativeStatusEffects {
            get {
                return ResourceManager.GetString("RestoreFullHPAndPPAndHealAllNegativeStatusEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal HP or increase max HP if at max.
        /// </summary>
        public static string RestoreHP {
            get {
                return ResourceManager.GetString("RestoreHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore HP equal to a percentage of maximum HP.
        /// </summary>
        public static string RestoreHPPercent {
            get {
                return ResourceManager.GetString("RestoreHPPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore HP with a boost in sunny weather or penalty in bad weather.
        /// </summary>
        public static string RestoreHPWithBoostInSunnyWeather {
            get {
                return ResourceManager.GetString("RestoreHPWithBoostInSunnyWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore PP on all of the target&apos;s moves.
        /// </summary>
        public static string RestorePPAll {
            get {
                return ResourceManager.GetString("RestorePPAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore PP on one of the target&apos;s moves.
        /// </summary>
        public static string RestorePPOne {
            get {
                return ResourceManager.GetString("RestorePPOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal all hidden traps on the floor.
        /// </summary>
        public static string RevealAllTraps {
            get {
                return ResourceManager.GetString("RevealAllTraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal the entire floor.
        /// </summary>
        public static string RevealFloor {
            get {
                return ResourceManager.GetString("RevealFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn a projectile that flies towards the stairs.
        /// </summary>
        public static string RevealStairsDirection {
            get {
                return ResourceManager.GetString("RevealStairsDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse stat changes.
        /// </summary>
        public static string ReverseStatChanges {
            get {
                return ResourceManager.GetString("ReverseStatChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal the last move used by the target.
        /// </summary>
        public static string SealLastUsedMove {
            get {
                return ResourceManager.GetString("SealLastUsedMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal all moves from enemies that the user also knows.
        /// </summary>
        public static string SealMovesKnownByUser {
            get {
                return ResourceManager.GetString("SealMovesKnownByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal a random move.
        /// </summary>
        public static string SealRandomMove {
            get {
                return ResourceManager.GetString("SealRandomMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user&apos;s and target&apos;s HP to the average of both HPs.
        /// </summary>
        public static string SetHPToAverage {
            get {
                return ResourceManager.GetString("SetHPToAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a Spikes Trap.
        /// </summary>
        public static string SetSpikesTrap {
            get {
                return ResourceManager.GetString("SetSpikesTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a Stealth Rock Trap.
        /// </summary>
        public static string SetStealthRockTrap {
            get {
                return ResourceManager.GetString("SetStealthRockTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace target&apos;s Ability with Insomnia.
        /// </summary>
        public static string SetTargetAbilityToInsomnia {
            get {
                return ResourceManager.GetString("SetTargetAbilityToInsomnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace target&apos;s Ability with Simple.
        /// </summary>
        public static string SetTargetAbilityToSimple {
            get {
                return ResourceManager.GetString("SetTargetAbilityToSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set target&apos;s HP to a percentage of max HP.
        /// </summary>
        public static string SetTargetHPToPercentageOfMaximum {
            get {
                return ResourceManager.GetString("SetTargetHPToPercentageOfMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a Toxic Spikes Trap.
        /// </summary>
        public static string SetToxicSpikesTrap {
            get {
                return ResourceManager.GetString("SetToxicSpikesTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user&apos;s HP to a percentage of max HP.
        /// </summary>
        public static string SetUserHPToPercentageOfMaximum {
            get {
                return ResourceManager.GetString("SetUserHPToPercentageOfMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab target, fly and apply Sky Drop status (first turn of Sky Drop).
        /// </summary>
        public static string SkyDropFirstTurn {
            get {
                return ResourceManager.GetString("SkyDropFirstTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop target and deal damage (second turn of Sky Drop).
        /// </summary>
        public static string SkyDropSecondTurn {
            get {
                return ResourceManager.GetString("SkyDropSecondTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown secondary effect applied by Smack Down.
        /// </summary>
        public static string SmackDownSecondaryEffect {
            get {
                return ResourceManager.GetString("SmackDownSecondaryEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn an enemy Ditto nearby.
        /// </summary>
        public static string SpawnDitto {
            get {
                return ResourceManager.GetString("SpawnDitto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn a random wild Pokémon or give a random rare item.
        /// </summary>
        public static string SpawnPokemonOrGiveRandomItem {
            get {
                return ResourceManager.GetString("SpawnPokemonOrGiveRandomItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn an enemy Stunfisk nearby.
        /// </summary>
        public static string SpawnStunfisk {
            get {
                return ResourceManager.GetString("SpawnStunfisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spend HP equal to a percentage of max HP.
        /// </summary>
        public static string SpendHP {
            get {
                return ResourceManager.GetString("SpendHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal damage based on stockpile count.
        /// </summary>
        public static string SpitUp {
            get {
                return ResourceManager.GetString("SpitUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump over the target until the next square not occupied by a creature in a straight line.
        /// </summary>
        public static string SplashBounce {
            get {
                return ResourceManager.GetString("SplashBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unconfirmed) Select only targets affected by the specified status effect.
        /// </summary>
        public static string StatusSelect {
            get {
                return ResourceManager.GetString("StatusSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unconfirmed) Select only targets affected by the specified status effect.
        /// </summary>
        public static string StatusSelect2 {
            get {
                return ResourceManager.GetString("StatusSelect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steal target&apos;s item.
        /// </summary>
        public static string Steal {
            get {
                return ResourceManager.GetString("Steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Stealth Rock damage.
        /// </summary>
        public static string StealthRockDamage {
            get {
                return ResourceManager.GetString("StealthRockDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase stockpile count.
        /// </summary>
        public static string Stockpile {
            get {
                return ResourceManager.GetString("Stockpile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take recoil damage from Struggle.
        /// </summary>
        public static string StruggleRecoilDamage {
            get {
                return ResourceManager.GetString("StruggleRecoilDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon a team of three helpers.
        /// </summary>
        public static string SummonHelpers {
            get {
                return ResourceManager.GetString("SummonHelpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon a random number of monsters.
        /// </summary>
        public static string SummonMonsters {
            get {
                return ResourceManager.GetString("SummonMonsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport all teammates around the target.
        /// </summary>
        public static string SurroundTarget {
            get {
                return ResourceManager.GetString("SurroundTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal HP based on stockpile count.
        /// </summary>
        public static string Swallow {
            get {
                return ResourceManager.GetString("Swallow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap user&apos;s and target&apos;s Abilities.
        /// </summary>
        public static string SwapAbility {
            get {
                return ResourceManager.GetString("SwapAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Attack and Special Attack boosts and multipliers between attacker and target.
        /// </summary>
        public static string SwapAttackAndSpAttackBoosts {
            get {
                return ResourceManager.GetString("SwapAttackAndSpAttackBoosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap raw Attack stat with raw Defense stat.
        /// </summary>
        public static string SwapAttackWithDefense {
            get {
                return ResourceManager.GetString("SwapAttackWithDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Defense and Special Defense boosts and multipliers between attacker and target.
        /// </summary>
        public static string SwapDefenseAndSpDefenseBoosts {
            get {
                return ResourceManager.GetString("SwapDefenseAndSpDefenseBoosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap the user&apos;s and target&apos;s current HP.
        /// </summary>
        public static string SwapHP {
            get {
                return ResourceManager.GetString("SwapHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap all stat boosts and multipliers (except Speed) between attacker and target.
        /// </summary>
        public static string SwapStatBoostsExceptSpeed {
            get {
                return ResourceManager.GetString("SwapStatBoostsExceptSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch user&apos;s and target&apos;s held items.
        /// </summary>
        public static string SwitchHeldItems {
            get {
                return ResourceManager.GetString("SwitchHeldItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch places between user and target.
        /// </summary>
        public static string SwitchPlaces {
            get {
                return ResourceManager.GetString("SwitchPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch places with the teammate directly behind user.
        /// </summary>
        public static string SwitchWithTeammateBehind {
            get {
                return ResourceManager.GetString("SwitchWithTeammateBehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unconfirmed) Take percentage of max HP as damage if user is Ghost type.
        /// </summary>
        public static string TakeDamageIfGhost {
            get {
                return ResourceManager.GetString("TakeDamageIfGhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part two of Thief and Covet (unknown effect).
        /// </summary>
        public static string ThiefCovetPartTwo {
            get {
                return ResourceManager.GetString("ThiefCovetPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw the target at another Pokémon.
        /// </summary>
        public static string ThrowTargetAtOther {
            get {
                return ResourceManager.GetString("ThrowTargetAtOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw target to a random direction up to 10 tiles, causing 5 damage on collision.
        /// </summary>
        public static string ThrowTargetToARandomDirection {
            get {
                return ResourceManager.GetString("ThrowTargetToARandomDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer all negative status effects to the target and unseals all moves.
        /// </summary>
        public static string TransferNegativeStatusEffectsToTarget {
            get {
                return ResourceManager.GetString("TransferNegativeStatusEffectsToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform into the target.
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform all items in the room into random wild Pokémon.
        /// </summary>
        public static string TransformItemsIntoPokemon {
            get {
                return ResourceManager.GetString("TransformItemsIntoPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn a random item in the inventory into an Apple.
        /// </summary>
        public static string TurnRandomItemIntoApple {
            get {
                return ResourceManager.GetString("TurnRandomItemIntoApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unconfirmed) Select only targets of the specified type.
        /// </summary>
        public static string TypeSelect {
            get {
                return ResourceManager.GetString("TypeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown effect 125.
        /// </summary>
        public static string Unknown125 {
            get {
                return ResourceManager.GetString("Unknown125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown effect 147.
        /// </summary>
        public static string Unknown147 {
            get {
                return ResourceManager.GetString("Unknown147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown effect 236.
        /// </summary>
        public static string Unknown236 {
            get {
                return ResourceManager.GetString("Unknown236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown effect 237.
        /// </summary>
        public static string Unknown237 {
            get {
                return ResourceManager.GetString("Unknown237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport all teammates to the user.
        /// </summary>
        public static string SurroundUser {
            get {
                return ResourceManager.GetString("SurroundUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown effect 76.
        /// </summary>
        public static string Unknown76 {
            get {
                return ResourceManager.GetString("Unknown76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown effect 77.
        /// </summary>
        public static string Unknown77 {
            get {
                return ResourceManager.GetString("Unknown77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown effect 81.
        /// </summary>
        public static string Unknown81 {
            get {
                return ResourceManager.GetString("Unknown81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown effect 83.
        /// </summary>
        public static string Unknown83 {
            get {
                return ResourceManager.GetString("Unknown83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the last move used by the target.
        /// </summary>
        public static string UseLastMove {
            get {
                return ResourceManager.GetString("UseLastMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a move based on the current terrain.
        /// </summary>
        public static string UseMoveBasedOnTerrain {
            get {
                return ResourceManager.GetString("UseMoveBasedOnTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a random move from the enemy.
        /// </summary>
        public static string UseRandomEnemyMove {
            get {
                return ResourceManager.GetString("UseRandomEnemyMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a random known move.
        /// </summary>
        public static string UseRandomKnownMove {
            get {
                return ResourceManager.GetString("UseRandomKnownMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a random move.
        /// </summary>
        public static string UseRandomMove {
            get {
                return ResourceManager.GetString("UseRandomMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a random move from a teammate.
        /// </summary>
        public static string UseRandomTeammateMove {
            get {
                return ResourceManager.GetString("UseRandomTeammateMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp to a random place on the same floor.
        /// </summary>
        public static string Warp {
            get {
                return ResourceManager.GetString("Warp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp user and set user&apos;s HP to a percentage of current HP.
        /// </summary>
        public static string WarpAndSetHPToPercentOfCurrentHP {
            get {
                return ResourceManager.GetString("WarpAndSetHPToPercentOfCurrentHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp a random target to the front of the user.
        /// </summary>
        public static string WarpRandomTargetToFront {
            get {
                return ResourceManager.GetString("WarpRandomTargetToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp teammates around target.
        /// </summary>
        public static string WarpTeammatesAroundTarget {
            get {
                return ResourceManager.GetString("WarpTeammatesAroundTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp target to the room containing the stairs.
        /// </summary>
        public static string WarpToStairsRoom {
            get {
                return ResourceManager.GetString("WarpToStairsRoom", resourceCulture);
            }
        }
    }
}
