//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyEditor.RomEditor.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemKind {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemKind() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SkyEditor.RomEditor.Resources.Strings.ItemKind", typeof(ItemKind).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        internal static string Arrow {
            get {
                return ResourceManager.GetString("Arrow", resourceCulture);
            }
        }
        
        internal static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        internal static string Equip {
            get {
                return ResourceManager.GetString("Equip", resourceCulture);
            }
        }
        
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        internal static string Seed {
            get {
                return ResourceManager.GetString("Seed", resourceCulture);
            }
        }
        
        internal static string PP {
            get {
                return ResourceManager.GetString("PP", resourceCulture);
            }
        }
        
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        internal static string Orb {
            get {
                return ResourceManager.GetString("Orb", resourceCulture);
            }
        }
        
        internal static string Wand {
            get {
                return ResourceManager.GetString("Wand", resourceCulture);
            }
        }
        
        internal static string Evolution {
            get {
                return ResourceManager.GetString("Evolution", resourceCulture);
            }
        }
        
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        internal static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        internal static string Wazamachine {
            get {
                return ResourceManager.GetString("Wazamachine", resourceCulture);
            }
        }
        
        internal static string Brokenmachine {
            get {
                return ResourceManager.GetString("Brokenmachine", resourceCulture);
            }
        }
        
        internal static string Trap {
            get {
                return ResourceManager.GetString("Trap", resourceCulture);
            }
        }
        
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
    }
}
