//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyEditor.RomEditor.Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyEditor.RomEditor.Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply Mod.
        /// </summary>
        public static string Views_MainWindowView_ApplyModMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_ApplyModMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Automation.
        /// </summary>
        public static string Views_MainWindowView_AutomationMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_AutomationMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Create Change Script.
        /// </summary>
        public static string Views_MainWindowView_CreateAutomationScriptMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_CreateAutomationScriptMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Views_MainWindowView_FileMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_FileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Views_MainWindowView_OpenDirectoryMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_OpenDirectoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save As....
        /// </summary>
        public static string Views_MainWindowView_SaveDirectoryAsMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_SaveDirectoryAsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Views_MainWindowView_SaveMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_SaveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starters.
        /// </summary>
        public static string Views_Rtdx_RtdxRomView_StartersCollection {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxRomView_StartersCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move 1.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Move1 {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Move1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move 2.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Move2 {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Move2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move 3.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Move3 {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Move3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move 4.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Move4 {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Move4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Pokemon {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Pokemon", resourceCulture);
            }
        }
    }
}
