//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyEditor.RomEditor.Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyEditor.RomEditor.Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Files.
        /// </summary>
        public static string FileDialogFilter_CsFiles {
            get {
                return ResourceManager.GetString("FileDialogFilter_CsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua Files.
        /// </summary>
        public static string FileDialogFilter_LuaFiles {
            get {
                return ResourceManager.GetString("FileDialogFilter_LuaFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Files.
        /// </summary>
        public static string FileDialogFilter_ModFiles {
            get {
                return ResourceManager.GetString("FileDialogFilter_ModFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modpack Files.
        /// </summary>
        public static string FileDialogFilter_ModpackFiles {
            get {
                return ResourceManager.GetString("FileDialogFilter_ModpackFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modpack Creator.
        /// </summary>
        public static string ViewModels_Rtdx_Automation_ModpackCreatorViewModel_Name {
            get {
                return ResourceManager.GetString("ViewModels_Rtdx_Automation_ModpackCreatorViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Switch Micro SD.
        /// </summary>
        public static string ViewModels_Rtdx_Tutorial_CustomizeRomViewModel_LayeredFsOpenFolderDialogTitle {
            get {
                return ResourceManager.GetString("ViewModels_Rtdx_Tutorial_CustomizeRomViewModel_LayeredFsOpenFolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string ViewModels_Rtdx_Tutorial_CustomizeRomViewModel_Name {
            get {
                return ResourceManager.GetString("ViewModels_Rtdx_Tutorial_CustomizeRomViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string ViewModels_Rtdx_Tutorial_FinishedViewModel_Name {
            get {
                return ResourceManager.GetString("ViewModels_Rtdx_Tutorial_FinishedViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string ViewModels_Rtdx_Tutorial_IntroViewModel_Name {
            get {
                return ResourceManager.GetString("ViewModels_Rtdx_Tutorial_IntroViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string ViewModels_Rtdx_Tutorial_ModpackViewModel_Name {
            get {
                return ResourceManager.GetString("ViewModels_Rtdx_Tutorial_ModpackViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Directory.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_AddModDirectory {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_AddModDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_AddModFile {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_AddModFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_Build {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModAuthor {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModDescription {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled by Default.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModEnabled {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID (Must be unique across all mods).
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModId {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModName {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModpackAuthor {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModpackAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModpackDescription {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModpackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID (Must be unique across all modpacks).
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModpackId {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModpackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModpackName {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModpackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModpackTarget {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModpackTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModpackVersion {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModpackVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_Mods {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModTarget {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Views_Automation_ModpackCreatorView_ModVersion {
            get {
                return ResourceManager.GetString("Views_Automation_ModpackCreatorView_ModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply Mod.
        /// </summary>
        public static string Views_MainWindowView_ApplyModMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_ApplyModMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Automation.
        /// </summary>
        public static string Views_MainWindowView_AutomationMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_AutomationMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Create Change Script.
        /// </summary>
        public static string Views_MainWindowView_CreateAutomationScriptMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_CreateAutomationScriptMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Views_MainWindowView_FileMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_FileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modpack Creator.
        /// </summary>
        public static string Views_MainWindowView_ModpackCreatorMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_ModpackCreatorMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string Views_MainWindowView_OpenDirectoryMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_OpenDirectoryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save As....
        /// </summary>
        public static string Views_MainWindowView_SaveDirectoryAsMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_SaveDirectoryAsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Views_MainWindowView_SaveMenuItem {
            get {
                return ResourceManager.GetString("Views_MainWindowView_SaveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starters.
        /// </summary>
        public static string Views_Rtdx_RtdxRomView_StartersCollection {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxRomView_StartersCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move 1.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Move1 {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Move1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move 2.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Move2 {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Move2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move 3.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Move3 {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Move3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move 4.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Move4 {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Move4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon.
        /// </summary>
        public static string Views_Rtdx_RtdxStarterView_Pokemon {
            get {
                return ResourceManager.GetString("Views_Rtdx_RtdxStarterView_Pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may now customize the game to your liking. When you&apos;re done, click Save, and browse to the root of your Nintendo Switch Micro SD card. This will save files for Layered FS into your Atmosphere directory..
        /// </summary>
        public static string Views_Rtdx_Tutorial_CustomizeRomView_IntroText {
            get {
                return ResourceManager.GetString("Views_Rtdx_Tutorial_CustomizeRomView_IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Views_Rtdx_Tutorial_CustomizeRomView_SaveLayeredFs {
            get {
                return ResourceManager.GetString("Views_Rtdx_Tutorial_CustomizeRomView_SaveLayeredFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes have been saved to your Micro SD card. Once you safely eject it, you can launch Atmosphere and begin the game.
        ///
        ///Click Restart if you would like to start again from the beginning..
        /// </summary>
        public static string Views_Rtdx_Tutorial_FinishedView_IntroText {
            get {
                return ResourceManager.GetString("Views_Rtdx_Tutorial_FinishedView_IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Views_Rtdx_Tutorial_FinishedView_Restart {
            get {
                return ResourceManager.GetString("Views_Rtdx_Tutorial_FinishedView_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a ROM editor for Pokémon Mystery Dungeon: Rescue Team DX. To begin, press &quot;Open ROM Directory&quot;, and browse to the directory into which you have extracted your ROM..
        /// </summary>
        public static string Views_Rtdx_Tutorial_IntroView_IntroText {
            get {
                return ResourceManager.GetString("Views_Rtdx_Tutorial_IntroView_IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ROM Directory.
        /// </summary>
        public static string Views_Rtdx_Tutorial_IntroView_OpenRomDirectory {
            get {
                return ResourceManager.GetString("Views_Rtdx_Tutorial_IntroView_OpenRomDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Modpack.
        /// </summary>
        public static string Views_Rtdx_Tutorial_ModpackView_ApplyModpack {
            get {
                return ResourceManager.GetString("Views_Rtdx_Tutorial_ModpackView_ApplyModpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a modpack that you wish to use, please click &quot;Apply Modpack&quot;. Otherwise, click Next..
        /// </summary>
        public static string Views_Rtdx_Tutorial_ModpackView_IntroText {
            get {
                return ResourceManager.GetString("Views_Rtdx_Tutorial_ModpackView_IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Views_Rtdx_Tutorial_ModpackView_Next {
            get {
                return ResourceManager.GetString("Views_Rtdx_Tutorial_ModpackView_Next", resourceCulture);
            }
        }
    }
}
