using System.Collections.Generic;
using SkyEditor.RomEditor.Rtdx.Reverse;
using SkyEditor.RomEditor.Rtdx.Reverse.Const.pokemon;
using Creature = SkyEditor.RomEditor.Rtdx.Reverse.Const.creature.Index;

namespace SkyEditor.RomEditor.Rtdx.Domain.Structures
{
    public partial class PegasusActDatabase
    {
        public List<ActorData> ActorDataList = new List<ActorData>
        {
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO",
                debug_name = "チュンのすけ",
                raw_pokemonIndex = Creature.PIKACHUU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.HERO),
                pokemonIndexOffset = 0x0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PARTNER",
                debug_name = "ポケさぶろう",
                raw_pokemonIndex = Creature.FUSHIGIDANE,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.PARTNER),
                pokemonIndexOffset = 0xCC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PARTY1",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADON,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_partyId = ActorData.PartyID.PARTY1,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x190,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PARTY3",
                debug_name = null,
                raw_pokemonIndex = Creature.SANDAA,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_partyId = ActorData.PartyID.PARTY3,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x238,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PARTY2",
                debug_name = null,
                raw_pokemonIndex = Creature.FAIYAA,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_partyId = ActorData.PartyID.PARTY2,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2DC,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "IRAI1",
                debug_name = null,
                raw_pokemonIndex = Creature.PICHUU,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.IRAI1),
                pokemonIndexOffset = 0x380,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "IRAI2",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADON,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.IRAI2),
                pokemonIndexOffset = 0x438,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SIZE1",
                debug_name = null,
                raw_pokemonIndex = Creature.KOMORUU,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4F0,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SIZE2",
                debug_name = null,
                raw_pokemonIndex = Creature.BOOMANDA,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x58C,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SIZE3",
                debug_name = null,
                raw_pokemonIndex = Creature.HOERUKO,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x628,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SIZE4",
                debug_name = null,
                raw_pokemonIndex = Creature.HOERUOO,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6C4,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData
            {
                opt_specialName = new TextId(0),
                symbolName = "SIZE5",
                debug_name = null,
                raw_pokemonIndex = Creature.IWAAKU,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x760,
                pokemonIndexEditable = false
            },
            new ActorData
            {
                opt_specialName = new TextId(0),
                symbolName = "SIZE6",
                debug_name = null,
                raw_pokemonIndex = Creature.HAGANEERU,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7FC,
                pokemonIndexEditable = false
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "BATAFURII",
                debug_name = "バタフリー",
                raw_pokemonIndex = Creature.BATAFURII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x8A8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KYATAPII",
                debug_name = "キャタピー",
                raw_pokemonIndex = Creature.KYATAPII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x958,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PERIPPAA",
                debug_name = "ペリッパー",
                raw_pokemonIndex = Creature.PERIPPAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0xA04,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PERIPPAA2",
                debug_name = "ペリッパー",
                raw_pokemonIndex = Creature.PERIPPAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PERIPPAA3",
                debug_name = "ペリッパー",
                raw_pokemonIndex = Creature.PERIPPAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PERIPPAA4",
                debug_name = "ペリッパー",
                raw_pokemonIndex = Creature.PERIPPAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PERIPPAA5",
                debug_name = "ペリッパー",
                raw_pokemonIndex = Creature.PERIPPAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KOIRU",
                debug_name = "コイル",
                raw_pokemonIndex = Creature.KOIRU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.KOIRU),
                pokemonIndexOffset = 0xD4C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KOIRU2",
                debug_name = "コイル",
                raw_pokemonIndex = Creature.KOIRU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KOIRU3",
                debug_name = "コイル",
                raw_pokemonIndex = Creature.KOIRU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KOIRU4",
                debug_name = "コイル",
                raw_pokemonIndex = Creature.KOIRU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "REAKOIRU",
                debug_name = "レアコイル",
                raw_pokemonIndex = Creature.REAKOIRU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1010,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DAGUTORIO",
                debug_name = "ダグトリオ",
                raw_pokemonIndex = Creature.DAGUTORIO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x10C0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DIGUDA",
                debug_name = "ディグダ",
                raw_pokemonIndex = Creature.DIGUDA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1170,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "EAAMUDO",
                debug_name = "エアームド",
                raw_pokemonIndex = Creature.EAAMUDO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1220,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KAKUREON",
                debug_name = "カクレオン",
                raw_pokemonIndex = Creature.KAKUREON,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x12D0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KAKUREON2",
                debug_name = "カクレオン",
                raw_pokemonIndex = Creature.KAKUREON_AZUKI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1380,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PERUSHIAN",
                debug_name = "ペルシアン",
                raw_pokemonIndex = Creature.PERUSHIAN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1438,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PUKURIN",
                debug_name = "プクリン",
                raw_pokemonIndex = Creature.PUKURIN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x14E8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GOKURIN",
                debug_name = "ゴクリン",
                raw_pokemonIndex = Creature.GOKURIN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1594,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GARUURA",
                debug_name = "ガルーラ",
                raw_pokemonIndex = Creature.GARUURA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1650,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GOKURIN2",
                debug_name = "ゴクリン",
                raw_pokemonIndex = Creature.GOKURIN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HASUBURERO",
                debug_name = "ハスブレロ",
                raw_pokemonIndex = Creature.HASUBURERO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x17AC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "WATAKKO",
                debug_name = "ワタッコ",
                raw_pokemonIndex = Creature.WATAKKO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x185C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "MADATSUBOMI",
                debug_name = "マダツボミ",
                raw_pokemonIndex = Creature.MADATSUBOMI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x190C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "BURUU",
                debug_name = "ブルー",
                raw_pokemonIndex = Creature.BURUU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x19BC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GURANBURU",
                debug_name = "グランブル",
                raw_pokemonIndex = Creature.GURANBURU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1A6C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SAANAITO",
                debug_name = "サーナイト",
                raw_pokemonIndex = Creature.SAANAITO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1B1C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "ABUSORU",
                debug_name = "アブソル",
                raw_pokemonIndex = Creature.ABUSORU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1BCC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "MAKUNOSHITA",
                debug_name = "マクノシタ",
                raw_pokemonIndex = Creature.MAKUNOSHITA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1C98,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DAATENGU",
                debug_name = "ダーテング",
                raw_pokemonIndex = Creature.DAATENGU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1D48,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KONOHANA",
                debug_name = "コノハナ",
                raw_pokemonIndex = Creature.KONOHANA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1DF4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KONOHANA2",
                debug_name = "コノハナ",
                raw_pokemonIndex = Creature.KONOHANA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "FUUDIN",
                debug_name = "フーディン",
                raw_pokemonIndex = Creature.FUUDIN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x1F54,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "RIZAADON",
                debug_name = "リザードン",
                raw_pokemonIndex = Creature.RIZAADON,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2004,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "BANGIRASU",
                debug_name = "バンギラス",
                raw_pokemonIndex = Creature.BANGIRASU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x20B4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GENGAA",
                debug_name = "ゲンガー",
                raw_pokemonIndex = Creature.GENGAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2164,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "AABO",
                debug_name = "アーボ",
                raw_pokemonIndex = Creature.AABO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2214,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "CHAAREMU",
                debug_name = "チャーレム",
                raw_pokemonIndex = Creature.CHAAREMU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x22C4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "TORANSERU",
                debug_name = null,
                raw_pokemonIndex = Creature.TORANSERU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2374,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "WATAKKO2",
                debug_name = "ワタッコ",
                raw_pokemonIndex = Creature.WATAKKO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2424,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SANDAA",
                debug_name = "サンダー",
                raw_pokemonIndex = Creature.SANDAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x24D4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "NEITYIO",
                debug_name = "ネイティオ",
                raw_pokemonIndex = Creature.NEITYIO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x25A0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "NAMAZUN",
                debug_name = "ナマズン",
                raw_pokemonIndex = Creature.NAMAZUN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2650,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KYUUKON",
                debug_name = "キュウコン",
                raw_pokemonIndex = Creature.KYUUKON,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2700,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "FAIYAA",
                debug_name = "ファイヤー",
                raw_pokemonIndex = Creature.FAIYAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x27B0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "FURIIZAA",
                debug_name = "ファイヤー",
                raw_pokemonIndex = Creature.FURIIZAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x287C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GURAADON",
                debug_name = "グラードン",
                raw_pokemonIndex = Creature.GURAADON,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2948,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KAMEKKUSU",
                debug_name = "カメックス",
                raw_pokemonIndex = Creature.KAMEKKUSU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x29F8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "OKUTAN",
                debug_name = "オクタン",
                raw_pokemonIndex = Creature.OKUTAN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2AA8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GOROONYA",
                debug_name = "ゴローニャ",
                raw_pokemonIndex = Creature.GOROONYA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2B58,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "REKKUUZA",
                debug_name = "レックウザ",
                raw_pokemonIndex = Creature.REKKUUZA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2C08,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SOONANO",
                debug_name = "ソーナノ",
                raw_pokemonIndex = Creature.SOONANO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2CB8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SOONANSU",
                debug_name = "ソーナンス",
                raw_pokemonIndex = Creature.SOONANSU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2D68,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "MANKII",
                debug_name = "マンキー",
                raw_pokemonIndex = Creature.MANKII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x2E14,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "MANKII2",
                debug_name = "マンキー",
                raw_pokemonIndex = Creature.MANKII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "MANKII3",
                debug_name = "マンキー",
                raw_pokemonIndex = Creature.MANKII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "MANKII4",
                debug_name = "マンキー",
                raw_pokemonIndex = Creature.MANKII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "PATCHIIRU",
                debug_name = "パッチール",
                raw_pokemonIndex = Creature.PATCHIIRU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x30BC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "ENTEI",
                debug_name = "エンテイ",
                raw_pokemonIndex = Creature.ENTEI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x316C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "RAIKOU",
                debug_name = "ライコウ",
                raw_pokemonIndex = Creature.RAIKOU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x321C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SUIKUN",
                debug_name = "スイクン",
                raw_pokemonIndex = Creature.SUIKUN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x32CC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HOUOU",
                debug_name = "ホウオウ",
                raw_pokemonIndex = Creature.HOUOU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x337C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "MYUUTSUU",
                debug_name = "ミュウツー",
                raw_pokemonIndex = Creature.MYUUTSUU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x342C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "RATYIOSU",
                debug_name = "ラティオス",
                raw_pokemonIndex = Creature.RATYIOSU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x34DC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "RATYIASU",
                debug_name = "ラティアス",
                raw_pokemonIndex = Creature.RATYIASU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x358C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "JIRAACHI",
                debug_name = "ジラーチ",
                raw_pokemonIndex = Creature.JIRAACHI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x363C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DOOBURU",
                debug_name = "ドーブル",
                raw_pokemonIndex = Creature.DOOBURU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3704,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DOOBURU2",
                debug_name = "ラティオス",
                raw_pokemonIndex = Creature.DOOBURU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DOOBURU3",
                debug_name = "ラティオス",
                raw_pokemonIndex = Creature.DOOBURU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GONBE",
                debug_name = "ゴンベ",
                raw_pokemonIndex = Creature.GONBE,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3924,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "MYUU",
                debug_name = "ミュウ",
                raw_pokemonIndex = Creature.MYUU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x39D4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "REJIROKKU",
                debug_name = "レジロック",
                raw_pokemonIndex = Creature.REJIROKKU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3A84,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "REJIAISU",
                debug_name = "レジアイス",
                raw_pokemonIndex = Creature.REJIAISU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3B34,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "REJISUCHIRU",
                debug_name = "レジスチル",
                raw_pokemonIndex = Creature.REJISUCHIRU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3BE4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KAIOOGA",
                debug_name = "カイオーガ",
                raw_pokemonIndex = Creature.KAIOOGA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3C94,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "RUGIA",
                debug_name = "ルギア",
                raw_pokemonIndex = Creature.RUGIA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3D44,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DEOKISHISU_N",
                debug_name = "デオキシス",
                raw_pokemonIndex = Creature.DEOKISHISU_N,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3DF4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "RAICHUU",
                debug_name = "ライチュウ",
                raw_pokemonIndex = Creature.RAICHUU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3EA4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GORUBATTO",
                debug_name = "ゴルバット",
                raw_pokemonIndex = Creature.GORUBATTO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x3F54,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SAIDON",
                debug_name = "サイドン",
                raw_pokemonIndex = Creature.SAIDON,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4004,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "BARIYAADO",
                debug_name = "バリヤード",
                raw_pokemonIndex = Creature.BARIYAADO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x40B4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SUTORAIKU",
                debug_name = "ストライク",
                raw_pokemonIndex = Creature.SUTORAIKU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4164,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "KAIROSU",
                debug_name = "カイロス",
                raw_pokemonIndex = Creature.KAIROSU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4214,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "MEGANIUMU",
                debug_name = "メガニウム",
                raw_pokemonIndex = Creature.MEGANIUMU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x42C4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "EIPAMU",
                debug_name = "エイパム",
                raw_pokemonIndex = Creature.EIPAMU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4374,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "GOMAZOU",
                debug_name = "ゴマゾウ",
                raw_pokemonIndex = Creature.GOMAZOU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4424,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEREBII",
                debug_name = "セレビィ",
                raw_pokemonIndex = Creature.SEREBII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x44D4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_HITOKAGE",
                debug_name = null,
                raw_pokemonIndex = Creature.HITOKAGE,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4570,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_FUSHIGIDANE",
                debug_name = null,
                raw_pokemonIndex = Creature.FUSHIGIDANE,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4610,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_ZENIGAME",
                debug_name = null,
                raw_pokemonIndex = Creature.ZENIGAME,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x46AC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_PIKACHUU",
                debug_name = null,
                raw_pokemonIndex = Creature.PIKACHUU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x474C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_PIKACHUU_F",
                debug_name = null,
                raw_pokemonIndex = Creature.PIKACHUU,
                raw_formType = FormType.HIGH_FEMALE,
                bIsFemale = true,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x47E8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_CHIKORIITA",
                debug_name = null,
                raw_pokemonIndex = Creature.CHIKORIITA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4884,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_WANINOKO",
                debug_name = null,
                raw_pokemonIndex = Creature.WANINOKO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4920,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_HINOARASHI",
                debug_name = null,
                raw_pokemonIndex = Creature.HINOARASHI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x49BC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_ACHAMO",
                debug_name = null,
                raw_pokemonIndex = Creature.ACHAMO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4A58,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_ACHAMO_F",
                debug_name = null,
                raw_pokemonIndex = Creature.ACHAMO,
                raw_formType = FormType.HIGH_FEMALE,
                bIsFemale = true,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4AF4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_KIMORI",
                debug_name = null,
                raw_pokemonIndex = Creature.KIMORI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4B90,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_MIZUGOROU",
                debug_name = null,
                raw_pokemonIndex = Creature.MIZUGOROU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4C2C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_KODAKKU",
                debug_name = null,
                raw_pokemonIndex = Creature.KODAKKU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4CC8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_KARAKARA",
                debug_name = null,
                raw_pokemonIndex = Creature.KARAKARA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4D64,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_NYAASU",
                debug_name = null,
                raw_pokemonIndex = Creature.NYAASU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4E00,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_WANRIKII",
                debug_name = null,
                raw_pokemonIndex = Creature.WANRIKII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4E9C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_IIBUI",
                debug_name = null,
                raw_pokemonIndex = Creature.IIBUI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4F38,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_IIBUI_F",
                debug_name = null,
                raw_pokemonIndex = Creature.IIBUI,
                raw_formType = FormType.HIGH_FEMALE,
                bIsFemale = true,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x4FD4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_ENEKO",
                debug_name = null,
                raw_pokemonIndex = Creature.ENEKO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5070,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "SEIKAKU_RIZAADO",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x510C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_POPPO1",
                debug_name = null,
                raw_pokemonIndex = Creature.POPPO,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x51A8,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_POPPO2",
                debug_name = null,
                raw_pokemonIndex = Creature.POPPO,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5240,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_POPPO3",
                debug_name = null,
                raw_pokemonIndex = Creature.POPPO,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x52D8,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_PIJON1",
                debug_name = null,
                raw_pokemonIndex = Creature.PIJON,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5370,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_PIJON2",
                debug_name = null,
                raw_pokemonIndex = Creature.PIJON,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5408,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_PIJON3",
                debug_name = null,
                raw_pokemonIndex = Creature.PIJON,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x54A0,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_ONISUZUME1",
                debug_name = null,
                raw_pokemonIndex = Creature.ONISUZUME,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5538,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_ONISUZUME2",
                debug_name = null,
                raw_pokemonIndex = Creature.ONISUZUME,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x55D0,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_ONISUZUME3",
                debug_name = null,
                raw_pokemonIndex = Creature.ONISUZUME,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5668,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_SUBAME1",
                debug_name = null,
                raw_pokemonIndex = Creature.SUBAME,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5700,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_SUBAME2",
                debug_name = null,
                raw_pokemonIndex = Creature.SUBAME,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5798,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_SUBAME3",
                debug_name = null,
                raw_pokemonIndex = Creature.SUBAME,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5830,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_KYAMOME1",
                debug_name = null,
                raw_pokemonIndex = Creature.KYAMOME,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x58C8,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_KYAMOME2",
                debug_name = null,
                raw_pokemonIndex = Creature.KYAMOME,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5960,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "LO_KYAMOME3",
                debug_name = null,
                raw_pokemonIndex = Creature.KYAMOME,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x59F8,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DBG_PARTY_1",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADO,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5A9C,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DBG_PARTY_2",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADON,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5B48,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "DBG_PARTY_3",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADON_MEGA_X,
                raw_formType = FormType.NORMAL,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5BF4,
                pokemonIndexEditable = false  // Can't edit due to unsupported instruction 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_HITOKAGE",
                debug_name = null,
                raw_pokemonIndex = Creature.HITOKAGE,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5C98,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_FUSHIGIDANE",
                debug_name = null,
                raw_pokemonIndex = Creature.FUSHIGIDANE,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5D38,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_ZENIGAME",
                debug_name = null,
                raw_pokemonIndex = Creature.ZENIGAME,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5DD8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_PIKACHUU",
                debug_name = null,
                raw_pokemonIndex = Creature.PIKACHUU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5E78,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_CHIKORIITA",
                debug_name = null,
                raw_pokemonIndex = Creature.CHIKORIITA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5F18,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_WANINOKO",
                debug_name = null,
                raw_pokemonIndex = Creature.WANINOKO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x5FB8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_HINOARASHI",
                debug_name = null,
                raw_pokemonIndex = Creature.HINOARASHI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6058,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_ACHAMO",
                debug_name = null,
                raw_pokemonIndex = Creature.ACHAMO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x60F8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_KIMORI",
                debug_name = null,
                raw_pokemonIndex = Creature.KIMORI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6198,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_MIZUGOROU",
                debug_name = null,
                raw_pokemonIndex = Creature.MIZUGOROU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6238,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_KODAKKU",
                debug_name = null,
                raw_pokemonIndex = Creature.KODAKKU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x62D8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_KARAKARA",
                debug_name = null,
                raw_pokemonIndex = Creature.KARAKARA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6378,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_NYAASU",
                debug_name = null,
                raw_pokemonIndex = Creature.NYAASU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6418,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_WANRIKII",
                debug_name = null,
                raw_pokemonIndex = Creature.WANRIKII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x64B8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_IIBUI",
                debug_name = null,
                raw_pokemonIndex = Creature.IIBUI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6558,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_ENEKO",
                debug_name = null,
                raw_pokemonIndex = Creature.ENEKO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x65F8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_RIZAADO",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexEditable = false // Can't edit due to copied value 
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_FUSHIGISOU",
                debug_name = null,
                raw_pokemonIndex = Creature.FUSHIGISOU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6728,
                
                // TODO: this one doesn't work for some reason although it should
                // pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_KAMEERU",
                debug_name = null,
                raw_pokemonIndex = Creature.KAMEERU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x67C0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_RAICHUU",
                debug_name = null,
                raw_pokemonIndex = Creature.RAICHUU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6860,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_BEIRIIFU",
                debug_name = null,
                raw_pokemonIndex = Creature.BEIRIIFU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x68FC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_ARIGEITSU",
                debug_name = null,
                raw_pokemonIndex = Creature.ARIGEITSU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6998,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_MAGUMARASHI",
                debug_name = null,
                raw_pokemonIndex = Creature.MAGUMARASHI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6A34,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_WAKASHAMO",
                debug_name = null,
                raw_pokemonIndex = Creature.WAKASHAMO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6AD0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_JUPUTORU",
                debug_name = null,
                raw_pokemonIndex = Creature.JUPUTORU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6B6C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_NUMAKUROO",
                debug_name = null,
                raw_pokemonIndex = Creature.NUMAKUROO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6C08,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_GORUDAKKU",
                debug_name = null,
                raw_pokemonIndex = Creature.GORUDAKKU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6CA4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_GARAGARA",
                debug_name = null,
                raw_pokemonIndex = Creature.GARAGARA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6D40,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_PERUSHIAN",
                debug_name = null,
                raw_pokemonIndex = Creature.PERUSHIAN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6DE0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_GOORIKII",
                debug_name = null,
                raw_pokemonIndex = Creature.GOORIKII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6E7C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_SHAWAAZU",
                debug_name = null,
                raw_pokemonIndex = Creature.SHAWAAZU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6F18,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_SANDAASU",
                debug_name = null,
                raw_pokemonIndex = Creature.SANDAASU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x6FB4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_BUUSUTAA",
                debug_name = null,
                raw_pokemonIndex = Creature.BUUSUTAA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7050,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_EEFI",
                debug_name = null,
                raw_pokemonIndex = Creature.EEFI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x70EC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_BURAKKII",
                debug_name = null,
                raw_pokemonIndex = Creature.BURAKKII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7188,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_RIIFIA",
                debug_name = null,
                raw_pokemonIndex = Creature.RIIFIA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7224,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_GUREISHIA",
                debug_name = null,
                raw_pokemonIndex = Creature.GUREISHIA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x72C0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_NINFIA",
                debug_name = null,
                raw_pokemonIndex = Creature.NINFIA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x735C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_ENEKORORO",
                debug_name = null,
                raw_pokemonIndex = Creature.ENEKORORO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x73F8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_RIZAADON",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADON,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7498,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_FUSHIGIBANA",
                debug_name = null,
                raw_pokemonIndex = Creature.FUSHIGIBANA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7534,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_KAMEKKUSU",
                debug_name = null,
                raw_pokemonIndex = Creature.KAMEKKUSU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x75D4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_MEGANIUMU",
                debug_name = null,
                raw_pokemonIndex = Creature.MEGANIUMU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7674,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_OODAIRU",
                debug_name = null,
                raw_pokemonIndex = Creature.OODAIRU,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7710,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_BAKUFUUN",
                debug_name = null,
                raw_pokemonIndex = Creature.BAKUFUUN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x77AC,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_BASHAAMO",
                debug_name = null,
                raw_pokemonIndex = Creature.BASHAAMO,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7848,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_JUKAIN",
                debug_name = null,
                raw_pokemonIndex = Creature.JUKAIN,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x78E4,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_RAGURAAJI",
                debug_name = null,
                raw_pokemonIndex = Creature.RAGURAAJI,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7980,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_KAIRIKII",
                debug_name = null,
                raw_pokemonIndex = Creature.KAIRIKII,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7A1C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_FUSHIGIBANA_MEGA",
                debug_name = null,
                raw_pokemonIndex = Creature.FUSHIGIBANA_MEGA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7AB8,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_RIZAADON_MEGA_X",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADON_MEGA_X,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7B54,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_RIZAADON_MEGA_Y",
                debug_name = null,
                raw_pokemonIndex = Creature.RIZAADON_MEGA_Y,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7BF0,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_KAMEKKUSU_MEGA",
                debug_name = null,
                raw_pokemonIndex = Creature.KAMEKKUSU_MEGA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7C8C,
                pokemonIndexEditable = true  
            },
            new ActorData {
                opt_specialName = new TextId(0),
                symbolName = "HERO_TEST_RAGURAAJI_MEGA",
                debug_name = null,
                raw_pokemonIndex = Creature.RAGURAAJI_MEGA,
                raw_formType = FormType.HIGH,
                bIsFemale = false,
                opt_warehouseId = new PokemonWarehouseId(FixedWarehouseId.NULL),
                pokemonIndexOffset = 0x7D28,
                pokemonIndexEditable = true  
            },
        };
    }
}