using System;
using System.Collections.Generic;
using System.Text;

namespace SkyEditor.RomEditor.Rtdx.Reverse.window
{
	internal enum FaceType
	{
		FACE_TYPE_NORMAL,
		FACE_TYPE_HAPPY,
		FACE_TYPE_PAIN,
		FACE_TYPE_ANGRY,
		FACE_TYPE_THINK,
		FACE_TYPE_SAD,
		FACE_TYPE_WEEP,
		FACE_TYPE_SHOUT,
		FACE_TYPE_TEARS,
		FACE_TYPE_DECIDE,
		FACE_TYPE_GLADNESS,
		FACE_TYPE_EMOTION,
		FACE_TYPE_SURPRISE,
		FACE_TYPE_FAINT,
		FACE_TYPE_RELIEF,
		FACE_TYPE_CATCHBREATH,
		FACE_TYPE_SPECIAL01,
		FACE_TYPE_SPECIAL02,
		FACE_TYPE_SPECIAL03,
		FACE_TYPE_SPECIAL04,
		FACE_TYPE_SPECIAL05,
		FACE_TYPE_SPECIAL06,
		FACE_TYPE_SPECIAL07,
		FACE_TYPE_SPECIAL08,
		FACE_TYPE_SPECIAL09,
		FACE_TYPE_SPECIAL10,
		FACE_TYPE_SPECIAL11,
		FACE_TYPE_SPECIAL12,
		FACE_TYPE_SPECIAL13,
		FACE_TYPE_SPECIAL14,
		FACE_TYPE_SPECIAL15,
		FACE_TYPE_SPECIAL16,
		FACE_TYPE_MAX
	}
}
